"""create_daily_market_data

Revision ID: 555248ed3eef
Revises: 797f9229f6a2
Create Date: 2026-08-27 19:45:36.854565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '555248ed3eef'
down_revision: Union[str, None] = '797f9229f6a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_market_data',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('open', sa.Numeric(), nullable=False),
    sa.Column('high', sa.Numeric(), nullable=False),
    sa.Column('low', sa.Numeric(), nullable=False),
    sa.Column('close', sa.Numeric(), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.Column('adj_open', sa.Numeric(), nullable=False),
    sa.Column('adj_high', sa.Numeric(), nullable=False),
    sa.Column('adj_low', sa.Numeric(), nullable=False),
    sa.Column('adj_close', sa.Numeric(), nullable=False),
    sa.Column('adj_volume', sa.BigInteger(), nullable=False),
    sa.Column('dividend_cash', sa.Numeric(), nullable=False),
    sa.Column('split_factor', sa.Numeric(), nullable=False),
    sa.Column('return_1d', sa.Numeric(), nullable=True),
    sa.Column('gap_pct', sa.Numeric(), nullable=True),
    sa.Column('intraday_return', sa.Numeric(), nullable=True),
    sa.Column('range_pct', sa.Numeric(), nullable=True),
    sa.Column('drawdown_from_high', sa.Numeric(), nullable=True),
    sa.CheckConstraint('adj_volume >= 0', name='ck_daily_market_data_adj_volume_ge_0'),
    sa.CheckConstraint('high >= low', name='ck_daily_market_data_high_ge_low'),
    sa.CheckConstraint('volume >= 0', name='ck_daily_market_data_volume_ge_0'),
    sa.ForeignKeyConstraint(['date'], ['trading_days.date'], name='fk_daily_market_data_date'),
    sa.PrimaryKeyConstraint('date', 'symbol', name='pk_daily_market_data')
    )
    op.create_index('ix_daily_market_data_symbol_date', 'daily_market_data', ['symbol', 'date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_daily_market_data_symbol_date', table_name='daily_market_data')
    op.drop_table('daily_market_data')
    # ### end Alembic commands ###
