"""create_trading_days

Revision ID: 797f9229f6a2
Revises: 
Create Date: 2026-08-27 19:36:06.530288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '797f9229f6a2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trading_days',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('weekday', sa.SmallInteger(), nullable=False),
    sa.Column('month', sa.SmallInteger(), nullable=False),
    sa.Column('quarter', sa.SmallInteger(), nullable=False),
    sa.Column('year', sa.SmallInteger(), nullable=False),
    sa.Column('day_of_month', sa.SmallInteger(), nullable=False),
    sa.Column('week_of_year', sa.SmallInteger(), nullable=False),
    sa.Column('trading_day_of_month', sa.SmallInteger(), nullable=False),
    sa.Column('trading_day_of_year', sa.SmallInteger(), nullable=False),
    sa.Column('days_to_month_end', sa.SmallInteger(), nullable=False),
    sa.Column('is_month_end', sa.Boolean(), nullable=False),
    sa.Column('is_quarter_end', sa.Boolean(), nullable=False),
    sa.Column('is_year_end', sa.Boolean(), nullable=False),
    sa.Column('prev_trading_date', sa.Date(), nullable=True),
    sa.Column('next_trading_date', sa.Date(), nullable=True),
    sa.CheckConstraint('day_of_month BETWEEN 1 AND 31', name='ck_trading_days_day_of_month'),
    sa.CheckConstraint('days_to_month_end >= 0', name='ck_trading_days_days_to_month_end'),
    sa.CheckConstraint('month BETWEEN 1 AND 12', name='ck_trading_days_month'),
    sa.CheckConstraint('quarter BETWEEN 1 AND 4', name='ck_trading_days_quarter'),
    sa.CheckConstraint('trading_day_of_month >= 1', name='ck_trading_days_td_of_month'),
    sa.CheckConstraint('trading_day_of_year >= 1', name='ck_trading_days_td_of_year'),
    sa.CheckConstraint('week_of_year BETWEEN 1 AND 53', name='ck_trading_days_week_of_year'),
    sa.CheckConstraint('weekday BETWEEN 1 AND 5', name='ck_trading_days_weekday'),
    sa.PrimaryKeyConstraint('date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trading_days')
    # ### end Alembic commands ###
