"""create_market_outcomes

Revision ID: b8ed4f8d4839
Revises: 555248ed3eef
Create Date: 2026-08-27 20:19:30.882596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8ed4f8d4839'
down_revision: Union[str, None] = '555248ed3eef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_outcomes',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('return_1d', sa.Numeric(), nullable=True),
    sa.Column('return_3d', sa.Numeric(), nullable=True),
    sa.Column('return_5d', sa.Numeric(), nullable=True),
    sa.Column('return_10d', sa.Numeric(), nullable=True),
    sa.Column('return_20d', sa.Numeric(), nullable=True),
    sa.Column('max_up_5d', sa.Numeric(), nullable=True),
    sa.Column('max_down_5d', sa.Numeric(), nullable=True),
    sa.Column('max_up_20d', sa.Numeric(), nullable=True),
    sa.Column('max_down_20d', sa.Numeric(), nullable=True),
    sa.Column('positive_1d', sa.Boolean(), nullable=True),
    sa.Column('positive_5d', sa.Boolean(), nullable=True),
    sa.Column('positive_20d', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['date'], ['trading_days.date'], name='fk_market_outcomes_date'),
    sa.PrimaryKeyConstraint('date', 'symbol', name='pk_market_outcomes')
    )
    op.create_index('ix_market_outcomes_symbol_date', 'market_outcomes', ['symbol', 'date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_market_outcomes_symbol_date', table_name='market_outcomes')
    op.drop_table('market_outcomes')
    # ### end Alembic commands ###
